version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.1.2
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0
  ruby: circleci/ruby@2.0.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
references:

  # Docker Image Configs
  config_android: &config_android
    working_directory: ~/Modulization
    docker:
      - image: circleci/android:api-26-alpha
    resource_class: large
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      JVM_OPTS: -Xmx3048m
      GRADLE_OPTS: -Xmx3048m -Dkotlin.compiler.execution.strategy=in-process -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError
      TERM: dumb
      JAVA_HOME: /usr/lib/jvm
      ANDROID_HOME: /usr/local/android-sdk-linux

  # ---------------------------------------------------------------------------------------------------------------------
  # CACHE GRADLE
  # ---------------------------------------------------------------------------------------------------------------------
  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

  save_gradle_cache: &save_gradle_cache
    save_cache:
      paths:
        - ~/.gradle
        - ~/.m2
      key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

  # ---------------------------------------------------------------------------------------------------------------------
  # DOWNLOAD ANDROID DEPENDENCIES
  # ---------------------------------------------------------------------------------------------------------------------
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  # ---------------------------------------------------------------------------------------------------------------------
  # CACHE RUBY FOR FASTLANE
  # ---------------------------------------------------------------------------------------------------------------------
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: gems-{{ checksum "fastlane/release_notes.txt" }}

  save_gems_cache: &save_gems_cache
    save_cache:
      paths:
        - vendor/bundle
      key: gems-{{ checksum "fastlane/release_notes.txt" }}

  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle update --system || bundle install --path vendor/bundle

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  staging_distribution:
    <<: *config_android
    docker:
      - image: 'cimg/base:stable'
    steps:
      # Checkout the code as the first step.
      - checkout
      - ruby/install:
          version: '2.7'
      - *restore_gradle_cache
      - *restore_gems_cache
      - run:
          name: bundler install
          command: gem install bundler
      - run: sudo chmod +x ./gradlew
      - *ruby_dependencies
      - *save_gradle_cache
      - *save_gems_cache

      - run: ./gradlew assembleDebug

  build:
    docker:
      - image: cimg/android:2021.08.1
    steps:
      - checkout
      - run: sudo chmod +x ./gradlew
      - run: ./gradlew androidDependencies
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run: yes | sdkmanager "platforms;android-33" || exit 0
      - ruby/install:
          version: '3.0.1'
      - run: bundle install
      - run: bundle clean --force
      - run: bundle update fastlane
      - run:
          name: Run instrumentation tests in Firebase Test Lab
          command: bundle exec fastlane buildOnToCircleCI firebase_token=$FIREBASE_TOKEN

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  workflow:
    jobs:
      - build
